### PR TITLE
性能优化

### PR DESCRIPTION
**Pull request by donjan-deng**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner @basakest

**Comment by techoner** [comment]
@donjan-deng  Doing so will not trigger the observer .

**Comment by hsluoyz** [comment]
Reverted by: https://github.com/php-casbin/laravel-authz/pull/21

**Comment by donjan-deng** [comment]
@techoner new pr <https://github.com/php-casbin/laravel-authz/pull/22>

**Pull request merged**
