### PR TITLE
feat: implement remote fetching of the model.conf

### PR DESCRIPTION
**Pull request by francoisauclair911**
- Require Guzzle
- Added to config key for url path and cache time
- Added logic to fetch the .conf file and use it as a model.

### CODE REVIEW

**Comment by hsluoyz** [comment]
Fix: https://github.com/php-casbin/laravel-authz/issues/15

**Comment by hsluoyz** [comment]
@techoner

**Review by techoner — CHANGES_REQUESTED** [review]
@francoisauclair911 These changes should not cause the entire file to be modified, as well as the modification of blank lines, please modify the git configuration and recommit .

**Comment by francoisauclair911** [comment]
Fighting my IDE at every step but I'll finally merge the right thing

**Comment by francoisauclair911** [comment]
@techoner hopefully this works now ? 
Not sure how clean it looks, I can delete this and recreate new merge request if it helps

Cheers

**Comment by hsluoyz** [comment]
@francoisauclair911 plz squash your commits into one single commit.

And also fix the checks:

image

**Comment by techoner** [comment]
> @techoner hopefully this works now ?
> Not sure how clean it looks, I can delete this and recreate new merge request if it helps
> 
> Cheers

`.gitconfig` should ignore newlines and file mods
```
[core]
autocrlf = false
filemode = false
safecrlf = true
```

**Pull request closed without merging**
