### PR TITLE
feat: Support Casbin BatchAdapter interface

### PR DESCRIPTION
**Pull request by basakest**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner plz review.

**Comment by hsluoyz** [comment]
Fix: https://github.com/php-casbin/laravel-authz/issues/10

**Comment by hsluoyz** [comment]
@lvtu1124 please review.

**Comment by techoner** [comment]
@basakest Please refer to the commit message format of semantic-release : https://github.com/semantic-release/semantic-release#commit-message-format

**Pull request merged**
